version: "3"


services:
  db:
    image: postgres:14
    env_file: .env
    ports:
      - "5432:5432"
    restart: always

  redis:
    image: redis

  celery:
    restart: always
    build: .

    command: celery -A test_django worker -l INFO
    env_file: .env
    depends_on:
      - db
      - redis

  app:
    build: .
    ports:
      - "8000:8000"
    command: >
      sh -c "python3 ert/manage.py migrate &&
             python3 ert/manage.py runserver"
    env_file: .env
    depends_on:
      - db