# Generated by Django 3.2.7 on 2021-10-13 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=15)),
                ('short_description', models.CharField(max_length=50)),
                ('detailed_description', models.TextField(max_length=1000)),
            ],
        ),
    ]
